"use strict";
const CONFIG={
  eventDate:"2026-07-27T08:00:00+07:00",
  sheetApiUrl:"https://script.google.com/macros/s/AKfycby2KDH-WiHGPc0n0_ub0fQTS0QK0ZaCKydRiZpi6EnKhuLabbZLJ5AqNM8gQIvtirNEfw/exec",
  mapsUrl:"https://maps.app.goo.gl/srisqJtCEBJnpB8A6?g_st=ic"
};
const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
const opening=$("#opening"),main=$("#mainContent"),openBtn=$("#openInvitation"),musicButton=$("#musicButton"),music=$("#backgroundMusic");
const guest=new URLSearchParams(location.search).get("to");if(guest)$("#guestName").textContent=guest.slice(0,80);
openBtn.addEventListener("click",async()=>{opening.classList.add("is-hidden");main.hidden=false;musicButton.hidden=false;document.body.style.overflow="";initReveal();try{await music.play();musicButton.classList.add("is-playing");musicButton.textContent="❚❚";}catch{}setTimeout(()=>opening.remove(),900)});
document.body.style.overflow="hidden";
musicButton.addEventListener("click",async()=>{if(music.paused){try{await music.play();musicButton.classList.add("is-playing");musicButton.textContent="❚❚"}catch{musicButton.title="Tambahkan assets/music.mp3 terlebih dahulu"}}else{music.pause();musicButton.classList.remove("is-playing");musicButton.textContent="♪"}});
function initReveal(){const els=$$(".reveal");if(!("IntersectionObserver" in window)){els.forEach(e=>e.classList.add("is-visible"));return}const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");obs.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>obs.observe(e))}
function tick(){const diff=new Date(CONFIG.eventDate)-new Date();const ids=[["days",86400000],["hours",3600000],["minutes",60000],["seconds",1000]];if(diff<=0){ids.forEach(([id])=>$("#"+id).textContent="00");return}$("#days").textContent=String(Math.floor(diff/86400000)).padStart(2,"0");$("#hours").textContent=String(Math.floor(diff%86400000/3600000)).padStart(2,"0");$("#minutes").textContent=String(Math.floor(diff%3600000/60000)).padStart(2,"0");$("#seconds").textContent=String(Math.floor(diff%60000/1000)).padStart(2,"0")};tick();setInterval(tick,1000);
$("#saveCalendar").addEventListener("click",()=>{const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Undangan Zamzami Silvi//ID","BEGIN:VEVENT","UID:zamzami-silvi-20260727@example.com","DTSTAMP:20260722T000000Z","DTSTART:20260727T010000Z","DTEND:20260727T080000Z","SUMMARY:Akad Nikah & Resepsi Zamzami & Silvi","LOCATION:Kediaman Mempelai Wanita, Kamulan, Durenan, Kabupaten Trenggalek, Jawa Timur","DESCRIPTION:Akad nikah pukul 08.00 WIB dan resepsi pukul 10.00 WIB. Lokasi: "+CONFIG.mapsUrl,"END:VEVENT","END:VCALENDAR"].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([ics],{type:"text/calendar"}));a.download="akad-resepsi-zamzami-silvi.ics";a.click();URL.revokeObjectURL(a.href)});
const giftDialog = $("#giftDialog"); $("#openGift").addEventListener("click", () => {giftDialog.showModal();}); $("#closeGift").addEventListener("click", () => {giftDialog.close();}); giftDialog.addEventListener("click", (e) => {if (e.target === giftDialog) {giftDialog.close();}}); $$(".gift-copy").forEach((button) => {button.addEventListener("click", async () => {const number = button.dataset.copy;try {await navigator.clipboard.writeText(number); const oldText = button.innerHTML; button.innerHTML = "✓ Berhasil Disalin"; button.classList.add("is-success"); setTimeout(() => { button.innerHTML = oldText; button.classList.remove("is-success"); }, 1800); } catch {  button.innerHTML = "Salin Manual : " + number; } }); });
const lightbox=$("#lightbox"),lightboxImage=$("#lightboxImage");$$(".gallery__item").forEach(btn=>btn.addEventListener("click",()=>{lightboxImage.src=$("img",btn).src;lightbox.showModal()}));$("#closeLightbox").addEventListener("click",()=>lightbox.close());lightbox.addEventListener("click",e=>{if(e.target===lightbox)lightbox.close()});
const form=$("#wishForm"),status=$("#wishStatus"),submit=$("#wishSubmit");form.addEventListener("submit",async e=>{e.preventDefault();const payload={nama:$("#wishName").value.trim(),kehadiran:$("#attendance").value,ucapan:$("#wishMessage").value.trim()};if(payload.nama.length<2||payload.ucapan.length<3){setStatus("Mohon lengkapi nama dan ucapan.",true);return}submit.disabled=true;submit.textContent="Mengirim...";try{await fetch(CONFIG.sheetApiUrl,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload)});setStatus("Ucapan berhasil dikirim. Terima kasih!",false);form.reset()}catch(err){setStatus("Ucapan belum berhasil dikirim. Periksa deployment Apps Script.",true)}finally{submit.disabled=false;submit.textContent="Kirim Ucapan"}});
function setStatus(message,isError){status.textContent=message;status.className="form-status "+(isError?"is-error":"is-success")}
